version: 1

formatters:
    default:
        format: '%(asctime)s | %(levelname)-8s | %(name)s | %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
    file:
        format: '%(asctime)s | %(levelname)-8s | %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
    file:
        formatter: file
        class: logging.handlers.RotatingFileHandler
        maxBytes: 10000
        backupCount: 1
        filename: non.log
        level: DEBUG
    console:
        formatter: default
        class: logging.StreamHandler
        stream: ext://sys.stdout
        level: DEBUG

root:
    level: DEBUG
    handlers: [console]

loggers:
#    default:
#        level: DEBUG
#        handlers: [file, console]
    non:
        level: DEBUG
        handlers: [file]


